### ISSUE TITLE
Incompatible with recent Prisma.Skip type

### ISSUE THREAD

**Issue by bodinsamuel** [arthurfiorette/prisma-json-types-generator#413]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

```
    "@prisma/client": "5.22.0",
    "prisma": "5.22.0",
    "prisma-json-types-generator": "3.1.1"
```

### A minimal reproducible example

d

### Description

Hey,
Thanks for providing this library, I recently upgraded to 5.22.0 and my json types stopped working.

### Steps to Reproduce

- enable `strictUndefinedChecks` in the `previewFeatures` 
- creation and insertion start screaming.

### Expected Behavior

Working

**Comment by arthurfiorette** [comment]
please put a bit more effort into your minimal reproducible example.

**Comment by WikiRik** [comment]
I wasn't sure how to get a minimal reproducible example using this, but I do have a type definition before and after enabling `strictUndefinedChecks` (see docs on that [here](https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/null-and-undefined#strict-undefined-checks-preview-feature))

Without the json-types-generator the optional duration Json was generated as such; `duration?: NullableJsonNullValueInput | InputJsonValue`. When I enabled the strictUndefinedChecks it became `duration?: NullableJsonNullValueInput | InputJsonValue | $Types.Skip`. Since that is not one of the options in the `findNewSignature` function of this package, it was not changed in a proper way. I haven't tested it out, but possibly you just have to add an additonal case there that includes `$Types.Skip`

Hopefully that makes it more clear, otherwise I'll try to spend more time to get a reproducible example
