### ISSUE TITLE
How do I access a global namespace from another file

### ISSUE THREAD

**Issue by psecuresystem** [arthurfiorette/prisma-json-types-generator#53]
I cant seem to be able to access the global namespace I created from another file.
I created the global namespace in a package(internal package) and I'm trying to access it where I imported the package.

I created the global namespace in `globalNamespace.ts`
```
import 'prisma-json-types-generator'
declare global {
  namespace PrismaJsonTypes {
    // Details
  }
}
```

**Comment by jakeleventhal** [comment]
you should remove the `global` namespace, then export `PrismaJsonTypes`, and any of your interfaces/types declared inside.

**Comment by arthurfiorette** [comment]
The `prisma-json-types-generator` import is wrong and just imports unused code at runtime.

The readme says to you do the following: 

```
declare global {
  namespace PrismaJson {
    // you can use classes, interfaces, types, etc.
    type MyType = boolean;
  }
}
```

It probably is because your typescript setup is wrongly configured, but as you did not provide any reproducible example, neither on how you are trying to use the type or even the error it shows, I'm afraid I cannot help you.

Try checking if the file is getting included in your tsconfig, `isolatedModules` and/or importing it inside your index.ts file.
